### ISSUE TITLE
Illegal option -o pipefail

### ISSUE THREAD

**Issue by kdchambers** [amp-59/treez#1]
Running `sh "zig_lib/support/switch_build_runner.sh";` as suggested leads to the following error: 

`zig_lib/support/switch_build_runner.sh: 2: set: Illegal option -o pipefail`

But just invoking the file normally works. I.e `./zig_lib/support/switch_build_runner.sh`

Executable itself works fine :+1:

**Comment by amp-59** [comment]
Thanks. Removing `sh` makes no difference to me.
